trigger:
- master

pool: 
  name: Azure Pipelines 
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    jdkVersionOption: '1.8'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
